id = "umple"
name = "Umple"
version = "0.0.1"
schema_version = 1
authors = ["umple"]
description = "Umple language support: syntax highlighting, diagnostics, completion, go-to-definition"
repository = "https://github.com/umple/umple.zed"

[grammars.umple]
repository = "https://github.com/umple/umple-lsp"
rev = "a98e22f8905da3cfd1466d6f54cf5587b96d9658"
path = "packages/tree-sitter-umple"

[language_servers.umple-lsp]
name = "Umple LSP"
languages = ["Umple"]
